GET http://localhost:8080/rest_start_code_war_exploded/api/person/hobby/athletics

###
PUT http://localhost:8080/rest_start_code_war_exploded/api/address/edit/6
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"street": "ExampleStreet"}

###

DELETE http://localhost:8080/rest_start_code_war_exploded/api/address/delete/6