GET http://localhost:8080/rest_start_code_war_exploded/api/person/hobby/athletics

###
POST http://localhost:8080/api/hobby/add
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"name": "ExampleStreet", "description":  "Some description"}

###

DELETE http://localhost:8080/rest_start_code_war_exploded/api/address/delete/6